[phases.setup]
pkgs = [
    "php81",
    "php81Packages.composer",
    "php81Packages.bcmath",
    "php81Packages.curl",
    "php81Packages.mbstring",
    "php81Packages.pdo",
    "php81Packages.pdo_mysql",
    "php81Packages.tokenizer",
    "php81Packages.xml",
    "nodejs_20",
    "npm"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[variables]
NIXPACKS_NODE_VERSION = "20"
