# nixpacks.toml

# Definimos la fase de "setup" para instalar las dependencias del sistema.
[phases.setup]

# Creamos una lista unificada de paquetes para evitar conflictos.
# Aquí Nix instalará PHP, sus extensiones Y Node.js en una sola operación.
pkgs = [
    "php81",
    "php81Packages.composer",
    "php81Packages.bcmath",
    "php81Packages.curl",
    "php81Packages.mbstring",
    "php81Packages.pdo",
    "php81Packages.pdo_mysql",
    "php81Packages.tokenizer",
    "php81Packages.xml",

    # --- AÑADIMOS NODE.JS Y NPM AQUÍ ---
    # Elige la versión de Node.js que necesites. "nodejs_20" es una opción segura y reciente.
    # También podemos añadir yarn o pnpm si los usas.
    "nodejs_20", 
    "npm" 
    # Si usas yarn: "yarn"
    # Si usas pnpm: "pnpm"
]

# Opcional: Especifica la versión de Node.js a usar en el build.
[variables]
NIXPACKS_NODE_VERSION = "20"